# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import mmsca2.models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsca2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=160, validators=[mmsca2.models.validate_content]),
        ),
    ]
