# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20171231_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='news',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
