# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20171231_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='news',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
