# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20180103_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='creativity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='player',
            name='influence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='player',
            name='threat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
