# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_fixture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fixture',
            new_name='nextGame',
        ),
    ]
