# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20180201_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nextFix',
            new_name='Fixtures',
        ),
    ]
