# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_auto_20180201_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fixId',
            field=models.IntegerField(default=0),
        ),
    ]
