# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='playerId',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
